/**
 * RFC 9457 - Problem Details for HTTP APIs
 * @see https://datatracker.ietf.org/doc/html/rfc9457
 */

/**
 * Problem Details object as defined in RFC 9457.
 *
 * All members are optional per the spec. Problem types MAY extend
 * this with additional members using {@link ProblemDetail}.
 */
export interface ProblemDetailBase {
  /**
   * A URI reference that identifies the problem type.
   * When dereferenced, it SHOULD provide human-readable documentation.
   * Defaults to `"about:blank"` when absent.
   */
  type?: string;

  /** The HTTP status code generated by the origin server. */
  status?: number;

  /**
   * A short, human-readable summary of the problem type.
   * SHOULD NOT change from occurrence to occurrence.
   */
  title?: string;

  /** A human-readable explanation specific to this occurrence. */
  detail?: string;

  /**
   * A URI reference that identifies the specific occurrence
   * of the problem.
   */
  instance?: string;
}

/**
 * Problem Details with type-safe extension members.
 *
 * @example
 * ```ts
 * // Validation error with custom `errors` field
 * type ValidationProblem = ProblemDetail<{
 *   errors: { field: string; message: string }[];
 * }>;
 * ```
 */
export type ProblemDetail<T extends Record<string, unknown> = Record<string, unknown>> =
  ProblemDetailBase & T;

/**
 * The media type for Problem Details JSON responses.
 * @see https://datatracker.ietf.org/doc/html/rfc9457#section-3
 */
export const PROBLEM_JSON_CONTENT_TYPE = "application/problem+json" as const;

export interface HttpProblemInit {
  /** HTTP status code (required). */
  status: number;
  /** URI identifying the problem type. Defaults to `"about:blank"`. */
  type?: string;
  /** Short, human-readable summary of the problem type. */
  title?: string;
  /** Human-readable explanation specific to this occurrence. */
  detail?: string;
  /** URI identifying the specific occurrence of the problem. */
  instance?: string;
  /** Additional members as defined by the problem type. */
  extensions?: Record<string, unknown>;
}

/**
 * Throwable Error that serializes to an RFC 9457 Problem Details response.
 *
 * @example
 * ```ts
 * // Throw in a route handler — catch in app.onError()
 * throw new HttpProblem({ status: 400, title: "Bad Request", detail: "..." });
 *
 * // With extension members
 * throw new HttpProblem({
 *   status: 422,
 *   title: "Validation Failed",
 *   extensions: {
 *     errors: [{ field: "email", message: "Invalid format" }],
 *   },
 * });
 *
 * // Convert to a Response (works in any runtime)
 * return new HttpProblem({ status: 404, title: "Not Found" }).toResponse();
 * ```
 */
export class HttpProblem extends Error {
  readonly type: string;
  readonly status: number;
  readonly title: string;
  readonly detail?: string;
  readonly instance?: string;
  readonly extensions: Record<string, unknown>;

  constructor(init: HttpProblemInit) {
    super(init.detail ?? init.title ?? `HTTP ${init.status}`);
    this.name = "HttpProblem";
    this.type = init.type ?? "about:blank";
    this.status = init.status;
    this.title = init.title ?? "";
    this.detail = init.detail;
    this.instance = init.instance;
    this.extensions = init.extensions ?? {};
  }

  /** Serialize to a flat RFC 9457 Problem Details object. */
  toJSON(): ProblemDetail {
    return {
      type: this.type,
      status: this.status,
      title: this.title,
      ...(this.detail !== undefined && { detail: this.detail }),
      ...(this.instance !== undefined && { instance: this.instance }),
      ...this.extensions,
    };
  }

  /** Create a `Response` with `application/problem+json` content type. */
  toResponse(): Response {
    return new Response(JSON.stringify(this.toJSON()), {
      status: this.status,
      headers: { "Content-Type": PROBLEM_JSON_CONTENT_TYPE },
    });
  }
}
